### ISSUE TITLE
Enqueuer converts payload data from string to number

### ISSUE THREAD

**Issue by alexandreMelloTW** [enqueuer-land/enqueuer#66]
**Describe the bug**
Enqueuer converts the `publishers.payload` data from string to number even with quotes or `!!str`.

**To Reproduce**
1. Create a publisher that use a number as a string:
```
publishers:
- name: Request a tranfer
  type: http
  payload:
    amount:
      value: 1.12
      currency: BRL
    description: My Description
    beneficiaryDocument: "43259912045"
    originAccount: 123
  headers:
    Content-Type: application/json
  url: http://localhost:3000/transfer
  method: post
```
2. Execute enqueuer
3. Check the server log for the body received:
```
{
  "amount": {
    "value":1.12,
    "currency":"BRL"
  },
  "description":"My Description",
  "beneficiaryDocument":43259912045,
  "originAccount":123
}
```
**Expected behavior**
Request made by enqueuer should keep `beneficiaryDocument` as `string`:
```
{
  "amount": {
    "value":1.12,
    "currency":"BRL"
  },
  "description":"My Description",
  "beneficiaryDocument":"43259912045",
  "originAccount":123
}
```

**Desktop (please complete the following information):**
 - OS: MacOS X 
 - Version 10.15.5

**Comment by virgs** [comment]
Hm.. I believe it is a yaml issue.
I have suggestions that may help you. Unfortunately, I am not able to test it.
So, let me know if some worked:

```
publishers:
- name: Request a transfer
  type: http
  payload:
    amount:
      value: 1.12
      currency: BRL
    description: My Description
    beneficiaryDocument: `43259912045`
    originAccount: 123
  headers:
    Content-Type: application/json
  url: http://localhost:3000/transfer
  method: post
```

```
publishers:
- name: Request a transfer
  type: http
  payload:
    amount:
      value: 1.12
      currency: BRL
    description: My Description
    beneficiaryDocument: "'43259912045'"
    originAccount: 123
  headers:
    Content-Type: application/json
  url: http://localhost:3000/transfer
  method: post
```

I believe they should work.
Please, let me know if I got you answered.

**Comment by alexandreMelloTW** [comment]
Thank you for your time.
I tried you suggestions, but didn't work. I also tried JSON file injection with the same result.

Do you have another suggestion?

**Comment by virgs** [comment]
Hmm, this is weird, I was pretty sure they would work.

I have another one.
Given that I'm still not able to test it, let me know if it works.

It consists of taking advantage of `onInit` hook method and make sure the value is a number:

```
publishers:
- name: Request a transfer
  type: http
  onInit:
    script: this.payload.beneficiaryDocument = "43259912045" //Note the presence of quotes
  payload:
    amount:
      value: 1.12
      currency: BRL
    description: My Description
    originAccount: 123
  headers:
    Content-Type: application/json
  url: http://localhost:3000/transfer
  method: post
```

**Comment by virgs** [comment]
I managed to find time and tried the first suggestion I gave to you:

```
publishers:
  - name: Request a tranfer
    type: http
    onInit:
      script: console.log(typeof this.payload.beneficiaryDocument)
    payload:
      amount:
        value: 1.12
        currency: BRL
      description: My Description
      beneficiaryDocument: `43259912045`
      originAccount: 123
    headers:
      Content-Type: application/json
    url: http://localhost:3000/transfer
    method: post
subscriptions:
  - type: http
    endpoint: /transfer
    method: post
    port: 3000
    response:
      payload: hi
      status: 200
    onMessageReceived:
      script: console.log(typeof JSON.parse(body).beneficiaryDocument)
```

```
➜  git:(master) ✗ nqr gh.yml
[2020-06-29T21:10:58.458Z] [INFO] - Rocking and rolling
string
string
           [PASS]      gh.yml                                                             2      tests passing of 2      (100%) | executed in 27ms
   ----------------
           [PASS] enqueuer                                                                2      tests passing of 2      (100%) | executed in 32ms
[2020-06-29T21:10:58.867Z] [INFO] - Hope you had a great time
```

It looks like it works after all. I think it's worthy double checking the type of it in the server.
