### ISSUE TITLE
Create subscriptions predicates

### ISSUE THREAD

**Issue by virgs** [enqueuer-land/enqueuer#70]
**Is your feature request related to a problem? Please describe.**
Sometimes, while executing tests, is not unusual to receive not related messages. eg. You're testing a queue subscription while the system is up and running, therefore a lot of not test related messages may be consumed and the expected one ignored.

**Describe the solution you'd like**
It'd be interesting to explicitly declare which message you're interested. Let's say, I'm interested in messages with HTTP header `key: interesting-value`. I think this predicate should have the same params as the hooks scripts. Something like:
```
subscriptions:
    - type: mqtt
       ....
       predicate: JSON.parse(body).something === `interesting`
```
